/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb 
*/

// @ts-ignore


import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

export function Model(props:any) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={(nodes.material as THREE.Mesh).geometry} 
        material={materials['Material.001']} 
        rotation={[Math.PI / 2, 0, 0]} 
      />
    </group>
  )
}

export default Model;

useGLTF.preload('/model.glb')

